apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-app
  template:
    metadata:
      labels:
        app: json-app
    spec:
      containers:
        - name: json-container
          image: json:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
