version: "3.9"

services:
  gateway:
    build: gateway_svc/.
    environment:
      - JSON_SERVICE_URL=http://json:8080
      - ALGORITHM_SERVICE_URL=http://algorithm:8080
    ports:
      - "8080:8080"
    depends_on:
      - "json"
      - "algorithm"
  json:
    build: json_svc/.
  algorithm:
    build: algorithm_svc/.
